### ISSUE TITLE
`!expr` vs `eval.expr`

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/hotfun#41]
We have this in our report YAML. Does it need to get updated? I got the warning message below. FYI @ltin1214 

````
---
title: "Yip Management of Ureteral Obstruction and uppertract Recurrence"
date: "`r format(Sys.Date(), format='%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
  word_document:
    reference_docx: !expr here::here('scripts/templates/doc_template.docx')
bibliography: "`r here::here('templates/references.bib')`"
csl: "`r here::here('templates/european-urology.csl')`"
---
````

```r
Warning messages:
1: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
```
